package fr.humanbooster.ideanoval.business;
// Generated 13 avr. 2016 14:47:43 by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;

import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Alertecommentaire generated by hbm2java
 */
@Entity
@Table(name = "alertecommentaire")
@DiscriminatorValue("C")
public class AlerteCommentaire extends Alerte implements Serializable {

	private static final long serialVersionUID = -4591451112884483444L;
	@ManyToOne
	private Commentaire commentaire;
	
	public AlerteCommentaire() {
	}

	public AlerteCommentaire(Commentaire commentaire) {
		super();
		this.commentaire = commentaire;
	}

	public AlerteCommentaire(Utilisateur utilisateur, String raison, Date dateHeureAlerte) {
		super(utilisateur, raison, dateHeureAlerte);
		// TODO Auto-generated constructor stub
	}

	public Commentaire getCommentaire() {
		return commentaire;
	}

	public void setCommentaire(Commentaire commentaire) {
		this.commentaire = commentaire;
	}

}
