package fr.humanbooster.ideanoval.business;
// Generated 13 avr. 2016 14:47:43 by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.DiscriminatorColumn;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Alerte generated by hbm2java
 */
@Entity
@Inheritance(strategy=InheritanceType.SINGLE_TABLE)
@DiscriminatorColumn(name="TypeAlerte")
public class Alerte implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5996340360694829838L;
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)	
	private int idAlerte;
	
	@ManyToOne(fetch = FetchType.LAZY)
	private Utilisateur utilisateur;
		
	@Column(name = "raison", nullable = false, length = 250)
	private String raison;
	

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateHeureAlerte", length = 19)	
	private Date dateHeureAlerte;


	public Alerte(int idAlerte, Utilisateur utilisateur, String raison, Date dateHeureAlerte) {
		super();
		this.idAlerte = idAlerte;
		this.utilisateur = utilisateur;
		this.raison = raison;
		this.dateHeureAlerte = dateHeureAlerte;
	}


	public Alerte() {
		super();
		// TODO Auto-generated constructor stub
	}


	public Alerte(Utilisateur utilisateur, String raison, Date dateHeureAlerte) {
		this.utilisateur = utilisateur;
		this.raison = raison;
		this.dateHeureAlerte = dateHeureAlerte;
		
	}


	public int getIdAlerte() {
		return idAlerte;
	}


	public void setIdAlerte(int idAlerte) {
		this.idAlerte = idAlerte;
	}


	public Utilisateur getUtilisateur() {
		return utilisateur;
	}


	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}



	public String getRaison() {
		return raison;
	}


	public void setRaison(String raison) {
		this.raison = raison;
	}


	public Date getDateHeureAlerte() {
		return dateHeureAlerte;
	}


	public void setDateHeureAlerte(Date dateHeureAlerte) {
		this.dateHeureAlerte = dateHeureAlerte;
	}
	
	
}
