package fr.humanbooster.ideanoval.business;
// Generated 13 avr. 2016 14:47:43 by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Classement generated by hbm2java
 */
@Inheritance(strategy=InheritanceType.TABLE_PER_CLASS)
public abstract class Classement implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -639325895289963170L;
	
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateHeureCreation", nullable = false, length = 19)
	private Date dateHeureCreation;
	
	public Classement() {
	}

	public Classement(Date dateHeureCreation) {
		super();
		this.dateHeureCreation = dateHeureCreation;
	}

	public Date getDateHeureCreation() {
		return dateHeureCreation;
	}

	public void setDateHeureCreation(Date dateHeureCreation) {
		this.dateHeureCreation = dateHeureCreation;
	}


}
