package fr.humanbooster.ideanoval.business;
// Generated 13 avr. 2016 14:47:43 by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Classementbrains generated by hbm2java Cette classe définit le classement des
 * utilisateurs ayant posté le plus d'idées
 */
@Entity
@Table(name = "classementbrains")
public class ClassementBrains extends Classement implements Serializable {

	private static final long serialVersionUID = -3509291782124146525L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int idClassementBrains;

	@OneToMany(mappedBy = "classementBrains", fetch = FetchType.EAGER)
	private List<LigneClassementUtilisateur> ligneClassementUtilisateurs;

	public ClassementBrains() {
	}

	public ClassementBrains(Date dateHeureCreation, List<LigneClassementUtilisateur> ligneClassementUtilisateurs) {
		super(dateHeureCreation);
		this.ligneClassementUtilisateurs = ligneClassementUtilisateurs;
	}

	public int getIdClassementBrains() {
		return idClassementBrains;
	}

	public void setIdClassementBrains(int idClassementBrains) {
		this.idClassementBrains = idClassementBrains;
	}

	public List<LigneClassementUtilisateur> getLigneClassementUtilisateurs() {
		return ligneClassementUtilisateurs;
	}

	public void setLigneClassementUtilisateurs(List<LigneClassementUtilisateur> ligneClassementUtilisateurs) {
		this.ligneClassementUtilisateurs = ligneClassementUtilisateurs;
	}

}
