package fr.humanbooster.ideanoval.business;
// Generated 13 avr. 2016 14:47:43 by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Classementbuzzs generated by hbm2java
 * Cette classe definit le classement des idées le plus commentées
 */
@Entity
@Table(name = "classementbuzzs")
@DiscriminatorValue("B")

public class ClassementBuzzs extends ClassementIdee implements Serializable {
	
	private static final long serialVersionUID = 8627007189452584496L;

	public ClassementBuzzs() {
		super();
		// TODO Auto-generated constructor stub
	}
	public ClassementBuzzs(Date dateHeureCreation, List<LigneClassementIdee> ligneClassementIdee) {
		super(dateHeureCreation, ligneClassementIdee);
		// TODO Auto-generated constructor stub
	}

	
	
}
