package fr.humanbooster.ideanoval.business;
// Generated 13 avr. 2016 14:47:43 by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Commentaire generated by hbm2java
 */
@Entity
@Table(name = "commentaire")
public class Commentaire implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2516973700636872290L;
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int idCommentaire;
	
	@ManyToOne
	@JoinColumn(name = "idUtilisateur")
	private Utilisateur utilisateur;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idIdee", nullable = false)
	private Idee idee;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateHeureCommentaire", nullable = false, length = 19)
	private Date dateHeureCommentaire;
	
	@Column(name = "estDesactive", nullable = false)
	private Boolean estDesactive;
	
	@Column(name = "description", nullable = false, length = 255)
	private String description;
	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "commentaire")
	private Set<AlerteCommentaire> alerteCommentaires = new HashSet<AlerteCommentaire>(0);

	public Commentaire() {
	}
	
	
	public Commentaire(Utilisateur utilisateur, Idee idee, Date dateHeureCommentaire, Boolean estDesactive,
			String description, Set<AlerteCommentaire> alerteCommentaires) {
		super();
		this.utilisateur = utilisateur;
		this.idee = idee;
		this.dateHeureCommentaire = dateHeureCommentaire;
		this.estDesactive = estDesactive;
		this.description = description;
		this.alerteCommentaires = alerteCommentaires;
	}


	public Set<AlerteCommentaire> getAlerteCommentaires() {
		return alerteCommentaires;
	}


	public void setAlerteCommentaires(Set<AlerteCommentaire> alerteCommentaires) {
		this.alerteCommentaires = alerteCommentaires;
	}


	public int getIdCommentaire() {
		return idCommentaire;
	}

	public void setIdCommentaire(int idCommentaire) {
		this.idCommentaire = idCommentaire;
	}

	public Utilisateur getUtilisateur() {
		return utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	public Idee getIdee() {
		return idee;
	}

	public void setIdee(Idee idee) {
		this.idee = idee;
	}

	public Date getDateHeureCommentaire() {
		return dateHeureCommentaire;
	}

	public void setDateHeureCommentaire(Date dateHeureCommentaire) {
		this.dateHeureCommentaire = dateHeureCommentaire;
	}

	public Boolean getEstDesactive() {
		return estDesactive;
	}

	public void setEstDesactive(Boolean estDesactive) {
		this.estDesactive = estDesactive;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	
}
