package fr.humanbooster.ideanoval.business;
// Generated 13 avr. 2016 14:47:43 by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Utilisateur generated by hbm2java
 */
@Entity
@Table(name = "utilisateur")
@NamedQuery(name = "Utilisateur.findAll", query = "SELECT u FROM Utilisateur u")

public class Utilisateur implements Serializable {

	private static final long serialVersionUID = 1683870407253730127L;
	@OneToMany
	 private List<Alerte> alertes;
	
	@ManyToOne
	 private ClassementBrains classementBrain;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateInscription", nullable = false, length = 19)
	private Date dateInscription;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateSuppression", length = 19)	
	private Date dateSuppression;
	
	@Column(name = "email", nullable = false, length = 50)
	private String email;
	
	@ManyToOne
	private UtilisateurEtat etatUtilisateur;
	
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private int idUtilisateur;

	
	@Column(name = "motDePasse", nullable = false, length = 20)
	private String motDePasse;

	 @Column(name = "pseudo", nullable = false, length = 30)
	private String pseudo;

	@ManyToOne
	private UtilisateurRole roleUtilisateur;

	public Utilisateur() {
	}

	public Utilisateur(int idUtilisateur, String email, String motDePasse, String pseudo, Date dateInscription,
			Date dateSuppression, UtilisateurRole roleUtilisateur, UtilisateurEtat etatUtilisateur) {
		super();
		this.idUtilisateur = idUtilisateur;
		this.email = email;
		this.motDePasse = motDePasse;
		this.pseudo = pseudo;
		this.dateInscription = dateInscription;
		this.dateSuppression = dateSuppression;
		this.roleUtilisateur = roleUtilisateur;
		this.etatUtilisateur = etatUtilisateur;
	}

	public List<Alerte> getAlertes() {
		return alertes;
	}

	public ClassementBrains getClassementBrain() {
		return classementBrain;
	}

	public Date getDateInscription() {
		return dateInscription;
	}

	public Date getDateSuppression() {
		return dateSuppression;
	}

	public String getEmail() {
		return email;
	}

	public UtilisateurEtat getEtatUtilisateur() {
		return etatUtilisateur;
	}

	public int getIdUtilisateur() {
		return idUtilisateur;
	}

	public String getMotDePasse() {
		return motDePasse;
	}

	public String getPseudo() {
		return pseudo;
	}

	public UtilisateurRole getRoleUtilisateur() {
		return roleUtilisateur;
	}

	public void setAlertes(List<Alerte> alertes) {
		this.alertes = alertes;
	}

	public void setClassementBrain(ClassementBrains classementBrain) {
		this.classementBrain = classementBrain;
	}

	public void setDateInscription(Date dateInscription) {
		this.dateInscription = dateInscription;
	}

	public void setDateSuppression(Date dateSuppression) {
		this.dateSuppression = dateSuppression;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public void setEtatUtilisateur(UtilisateurEtat etatUtilisateur) {
		this.etatUtilisateur = etatUtilisateur;
	}

	public void setIdUtilisateur(int idUtilisateur) {
		this.idUtilisateur = idUtilisateur;
	}

	public void setMotDePasse(String motDePasse) {
		this.motDePasse = motDePasse;
	}

	public void setPseudo(String pseudo) {
		this.pseudo = pseudo;
	}

	public void setRoleUtilisateur(UtilisateurRole roleUtilisateur) {
		this.roleUtilisateur = roleUtilisateur;
	}

	@Override
	public String toString() {
		return "Utilisateur [idUtilisateur=" + idUtilisateur + ", email=" + email + ", motDePasse=" + motDePasse
				+ ", pseudo=" + pseudo + ", dateInscription=" + dateInscription + ", dateSuppression=" + dateSuppression
				+ ", roleUtilisateur=" + roleUtilisateur + ", etatUtilisateur=" + etatUtilisateur + "]";
	}


}
