package fr.humanbooster.ideanoval.business;
// Generated 13 avr. 2016 14:47:43 by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Vote generated by hbm2java
 */
@Entity
@Table(name = "vote")
public class Vote implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7897202010407018188L;
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idVote", unique = true, nullable = false)
	private int idVote;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idIdee", nullable = false)
	private Idee idee;

	@Column(name = "estTop", nullable = false)
	private Boolean estTop;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateVote", nullable = false, length = 19)
	private Date dateVote;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idUtilisateur", nullable = false)
	private Utilisateur utilisateur;

	public Vote() {
	}

	public Vote(Idee idee, Boolean estTop, Date dateVote, Utilisateur utilisateur) {
		super();
		this.idee = idee;
		this.estTop = estTop;
		this.dateVote = dateVote;
		this.utilisateur = utilisateur;
	}

	public int getIdVote() {
		return idVote;
	}

	public void setIdVote(int idVote) {
		this.idVote = idVote;
	}

	public Idee getIdee() {
		return idee;
	}

	public void setIdee(Idee idee) {
		this.idee = idee;
	}

	public Boolean getEstTop() {
		return estTop;
	}

	public void setEstTop(Boolean estTop) {
		this.estTop = estTop;
	}

	public Date getDateVote() {
		return dateVote;
	}

	public void setDateVote(Date dateVote) {
		this.dateVote = dateVote;
	}

	public Utilisateur getUtilisateur() {
		return utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

}
